import mongoose from "mongoose";
import { Alert } from "../models/Alert.js";
import { MaintenanceRecord } from "../models/MaintenanceRecord.js";
import { Vehicle, type VehicleAttrs } from "../models/Vehicle.js";
import { addDays, todayInBusinessTz } from "../utils/dates.js";
import type { MaintenanceType } from "@fleetify/shared";

export type MaintenanceEvaluation = {
  alertsCreated: number;
  pendingCreated: number;
  blocking: boolean;
};

export async function evaluateVehicleMaintenance(
  vehicle: mongoose.HydratedDocument<VehicleAttrs>,
  session?: mongoose.ClientSession,
): Promise<MaintenanceEvaluation> {
  const today = todayInBusinessTz();
  let alertsCreated = 0;
  let pendingCreated = 0;
  let blocking = false;

  for (const rule of vehicle.maintenanceRules) {
    const lastCompleted = await MaintenanceRecord.findOne({
      vehicleId: vehicle._id,
      type: rule.type,
      status: "Completed",
    })
      .sort({ servicedDate: -1, createdAt: -1 })
      .session(session ?? null);

    const dueOdometer =
      rule.intervalKm > 0
        ? (lastCompleted
            ? (lastCompleted.odometerAtServiceKm ?? vehicle.currentOdometerKm)
            : 0) + rule.intervalKm
        : undefined;
    const dueDate =
      rule.intervalDays > 0
        ? addDays(lastCompleted?.servicedDate ?? vehicle.createdAt.toISOString().slice(0, 10), rule.intervalDays)
        : undefined;

    const odometerOverdue = dueOdometer !== undefined && vehicle.currentOdometerKm >= dueOdometer;
    const dateOverdue = dueDate !== undefined && today >= dueDate;
    if (!odometerOverdue && !dateOverdue) {
      continue;
    }

    const key = `maint:${String(vehicle._id)}:${rule.type}:${dueOdometer ?? "none"}:${dueDate ?? "none"}`;
    const message = buildMessage(vehicle.licensePlate, rule.type, dueOdometer, dueDate);
    const existingAlert = await Alert.findOne({ key }).session(session ?? null);
    await Alert.findOneAndUpdate(
      { key },
      {
        $setOnInsert: {
          vehicleId: vehicle._id,
          category: "maintenance",
          key,
          severity: rule.isBlocking ? "urgent" : "warning",
          message,
          isResolved: false,
          dueOdometerKm: dueOdometer,
          dueDate,
        },
      },
      { upsert: true, new: true, session },
    );
    if (!existingAlert) {
      alertsCreated += 1;
    }

    const existingPending = await MaintenanceRecord.findOne({
      vehicleId: vehicle._id,
      type: rule.type,
      status: "Pending",
    }).session(session ?? null);
    if (!existingPending) {
      await MaintenanceRecord.create(
        [
          {
            vehicleId: vehicle._id,
            type: rule.type,
            nextDueOdometerKm: dueOdometer,
            nextDueDate: dueDate,
            costCents: 0,
            status: "Pending",
            isBlocking: rule.isBlocking,
            notes: "Generated by mileage and date maintenance engine",
          },
        ],
        { session },
      );
      pendingCreated += 1;
    }

    if (rule.isBlocking) {
      blocking = true;
    }
  }

  if (vehicle.inspectionExpiresAt.getTime() <= Date.now()) {
    const key = `insp:${String(vehicle._id)}:${vehicle.inspectionExpiresAt.toISOString().slice(0, 10)}`;
    await Alert.findOneAndUpdate(
      { key },
      {
        $setOnInsert: {
          vehicleId: vehicle._id,
          category: "inspection",
          key,
          severity: "urgent",
          message: `Inspection expired for ${vehicle.licensePlate}`,
          isResolved: false,
          dueDate: vehicle.inspectionExpiresAt.toISOString().slice(0, 10),
        },
      },
      { upsert: true, session },
    );
    blocking = true;
  }

  if (blocking && vehicle.status !== "Out of Service" && vehicle.status !== "Booked") {
    if (vehicle.status !== "In Maintenance") {
      vehicle.status = "In Maintenance";
      await vehicle.save({ session });
    }
  } else if (!blocking && vehicle.status === "In Maintenance") {
    vehicle.status = "Available";
    await vehicle.save({ session });
  }

  return { alertsCreated, pendingCreated, blocking };
}

export async function evaluateByVehicleId(
  vehicleId: mongoose.Types.ObjectId,
  session?: mongoose.ClientSession,
): Promise<MaintenanceEvaluation> {
  const vehicle = await Vehicle.findById(vehicleId).session(session ?? null);
  if (!vehicle) {
    return { alertsCreated: 0, pendingCreated: 0, blocking: false };
  }
  return evaluateVehicleMaintenance(vehicle, session);
}

function buildMessage(
  plate: string,
  type: MaintenanceType,
  dueOdometer?: number,
  dueDate?: string,
): string {
  const parts = [`${type} overdue for ${plate}`];
  if (dueOdometer !== undefined) parts.push(`due at ${dueOdometer} km`);
  if (dueDate) parts.push(`due ${dueDate}`);
  return parts.join(" - ");
}
